name = "Registry"
uuid = "f895ae59-e475-4102-8b85-ba81d7a5ee60"
repo = "https://github.com/itsdfish/Registry.jl"

[packages]
24e5ef78-50fe-477e-a5d7-9fd2ec18bc46 = { name = "QuantumPrisonersDilemmaModel", path = "Q/QuantumPrisonersDilemmaModel" }
27403de4-b1c2-4c44-95d8-36d2b6bff33e = { name = "ACTRPVT", path = "A/ACTRPVT" }
aeb53088-f60c-46c6-a6bd-4c0674b6a013 = { name = "QuantumEpisodicMemory", path = "Q/QuantumEpisodicMemory" }
df2e8839-b2b1-4723-be1d-fec23799ee0a = { name = "SocialSamplingTheory", path = "S/SocialSamplingTheory" }
eb72c636-9a01-4ecc-abce-d33068f7a378 = { name = "CategorizationModels", path = "C/CategorizationModels" }
