name = "Registry"
uuid = "f895ae59-e475-4102-8b85-ba81d7a5ee60"
repo = "https://github.com/itsdfish/Registry.jl"

[packages]
078a070c-0203-4da7-b1d6-6b458fb9d52e = { name = "CantStop", path = "C/CantStop" }
0ed30ee8-6cef-4eac-8e89-7848059aa71e = { name = "QuantumDynamicInconsistencyModels", path = "Q/QuantumDynamicInconsistencyModels" }
24e5ef78-50fe-477e-a5d7-9fd2ec18bc46 = { name = "QuantumPrisonersDilemmaModel", path = "Q/QuantumPrisonersDilemmaModel" }
260ba6b7-9af7-473a-b238-1a1a0638f266 = { name = "TrueAndErrorModels", path = "T/TrueAndErrorModels" }
2683bf95-d0b8-4c71-a7d3-b42f78bf1cf0 = { name = "RetirementPlanners", path = "R/RetirementPlanners" }
27403de4-b1c2-4c44-95d8-36d2b6bff33e = { name = "ACTRPVT", path = "A/ACTRPVT" }
96ca8dcf-183a-4ff5-ac3e-0011235b8f55 = { name = "Code2String", path = "C/Code2String" }
aeb53088-f60c-46c6-a6bd-4c0674b6a013 = { name = "QuantumEpisodicMemory", path = "Q/QuantumEpisodicMemory" }
df2e8839-b2b1-4723-be1d-fec23799ee0a = { name = "SocialSamplingTheory", path = "S/SocialSamplingTheory" }
eb72c636-9a01-4ecc-abce-d33068f7a378 = { name = "CategorizationModels", path = "C/CategorizationModels" }
