name = "Registry"
uuid = "f895ae59-e475-4102-8b85-ba81d7a5ee60"
repo = "https://github.com/itsdfish/Registry.jl"

[packages]
df2e8839-b2b1-4723-be1d-fec23799ee0a = { name = "SocialSamplingTheory", path = "S/SocialSamplingTheory" }
